const INVALID_REFRESH_TOKEN=process.env.REACT_APP_INVALID_REFRESH_TOKEN
const REFRESH_TOKEN_UNAUTHORIZED=process.env.REACT_APP_REFRESH_TOKEN_UNAUTHORIZED


const INVALID_ACCESS_TOKEN=process.env.REACT_APP_INVALID_ACCESS_TOKEN
const ACCESS_TOKEN_UNAUTHORIZED=process.env.REACT_APP_ACCESS_TOKEN_UNAUTHORIZED

const INVALID_VALIDATION_TOKEN=process.env.REACT_APP_INVALID_VALIDATION_TOKEN
const VALIDATION_TOKEN_UNAUTHORIZED=process.env.REACT_APP_VALIDATION_TOKEN_UNAUTHORIZED
const VALIDATION_TOKEN_MISMATCH=process.env.REACT_APP_VALIDATION_TOKEN_MISMATCH

const REACT_APP_USER_NOT_CHAT_ADMIN=process.env.REACT_APP_REACT_APP_USER_NOT_CHAT_ADMIN
const USER_NOT_IN_CHAT=process.env.REACT_APP_USER_NOT_IN_CHAT


export {
    INVALID_REFRESH_TOKEN,
    REFRESH_TOKEN_UNAUTHORIZED,

    INVALID_ACCESS_TOKEN,
    ACCESS_TOKEN_UNAUTHORIZED,

    INVALID_VALIDATION_TOKEN,
    VALIDATION_TOKEN_UNAUTHORIZED,
    VALIDATION_TOKEN_MISMATCH,
    
    REACT_APP_USER_NOT_CHAT_ADMIN,
    USER_NOT_IN_CHAT
}