const INVALID_REFRESH_TOKEN='INVALID_REFRESH_TOKEN'
const REFRESH_TOKEN_UNAUTHORIZED='REFRESH_TOKEN_UNAUTHORIZED'

const INVALID_ACCESS_TOKEN='INVALID_ACCESS_TOKEN'
const ACCESS_TOKEN_UNAUTHORIZED='ACCESS_TOKEN_UNAUTHORIZED'

const INVALID_VALIDATION_TOKEN='INVALID_VALIDATION_TOKEN'
const VALIDATION_TOKEN_UNAUTHORIZED='VALIDATION_TOKEN_UNAUTHORIZED'
const VALIDATION_TOKEN_MISMATCH='VALIDATION_TOKEN_MISMATCH'


const USER_NOT_CHAT_ADMIN='USER_NOT_CHAT_ADMIN'
const USER_NOT_IN_CHAT='USER_NOT_IN_CHAT'


export {
    INVALID_REFRESH_TOKEN,
    REFRESH_TOKEN_UNAUTHORIZED,
    INVALID_ACCESS_TOKEN,
    ACCESS_TOKEN_UNAUTHORIZED,
    INVALID_VALIDATION_TOKEN,
    VALIDATION_TOKEN_UNAUTHORIZED,
    VALIDATION_TOKEN_MISMATCH,
    USER_NOT_CHAT_ADMIN,
    USER_NOT_IN_CHAT,
}